# Generated by Django 3.1.7 on 2021-03-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0002_auto_20210310_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('file', models.FileField(upload_to='materials/')),
                ('material_type', models.CharField(choices=[('theory', 'Theoretical material'), ('practice', 'Practical')], default='theory', max_length=25)),
                ('lesson', models.ManyToManyField(to='lessons.Lesson')),
            ],
        ),
    ]
