# Generated by Django 3.1.7 on 2021-03-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20210302_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[("Didn't start", "Didn't start"), ('Start', 'Start'), ('Ended', 'Ended')], default="Didn't start", max_length=20),
        ),
    ]
