# Generated by Django 3.1.7 on 2021-03-02 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20210302_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[("Didn't start", 'DIDNT'), ('Start', 'START'), ('Ended', 'ENDED')], default="Didn't start", max_length=20),
        ),
    ]
